package Lelf::Phonebook::Model::Phonebook;

use Modern::Perl;
use base 'Catalyst::Model::DBIC::Schema';

use Moose;
use namespace::autoclean;
use MooseX::NonMoose;

__PACKAGE__->config(
    schema_class => 'Lelf::Phonebook::Schema::Phonebook',
    
    connect_info => {
        dsn => 'dbi:SQLite:phonebook.db',
        user => '',
        password => '',
    }
);




sub valid_person {
  my ($p) = @_;

  #(sort keys %$p) ~~ (sort qw{id name phones}) or return 0;
  
  return 1;
}

sub people_names {
    my ($self) = @_;

    return $self->resultset('Phonebook')->search({}, { columns => [qw{id name}] })->all;
}

sub update_person {
    
}

sub create_person {
  my ($self, $p) = @_;

  return undef unless valid_person($p);

  my $created = $self->resultset('Phonebook')->create($p);

  return $created;
}

sub find_person {
    my ($self, $id) = @_;

    my $o = $self->resultset('Phonebook')->find($id);

}





=head1 NAME

Lelf::Phonebook::Model::Phonebook - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Lelf::Phonebook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Lelf::Phonebook::Schema::Phonebook>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Anton Nikishaev

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
